#!/bin/bash;
#setup
#config

 clear
white="\033[1;37m"
purple="\033[0;35m"
grey="\033[0;37m"
red="\033[1;31m"
green="\033[1;32m"
yellow="\033[1;33m"
Purple="\033[0;35m"
Cyan="\033[0;36m"
Cafe="\033[0;33m"
Fiuscha="\033[0;35m"
blue="\033[1;34m"
nc="\e[0m"

echo
  echo
  echo
printf " ____________________________"
printf "| autor: \e[1;31m @phellipe_011 \e[0m    \e[1;37m |\e[0m"
printf "| versão:\e[1;31m 1.2 \e[0m              \e[1;37m |\e[0m"
printf "|____________________________|"
 echo -e
 echo -e
         setterm --foreground "cyan"
   echo "     instalando pacotes..."
   echo
   apt-get update > install.log
   echo
   pkg install php
      echo
         setterm --foreground "green"
      echo " > php instalado "
      echo
      echo
   pkg install cowsay
         setterm --foreground "green"
      echo " > cowsay instalado "
     echo
      echo
   pkg install python
         setterm --foreground "green"
      echo " > python instalado "
     echo
      echo
   pkg install python2
         setterm --foreground "green"
      echo " > python2 instalado "
     echo
      echo
   pkg install ssh
         setterm --foreground "green"
      echo " > ssh instalado "
   echo
   echo
             setterm --foreground "cyan"
   echo " Dando permissao para executar..."
     
     echo
    echo
   echo
        setterm --foreground "green"
    toilet -f slant "    PRONTO!"
echo
        setterm --foreground "white"
echo " •configurado "
echo " •update"
echo
